[workspace]
members = [
    "crates/core",
    "crates/ffi",
    "crates/resource-build",
    "crates/sanitize-binary",
    "platforms/cli"
]
resolver = "2"

[workspace.package]
version = "1.0.2"
edition = "2021"
license = "GPL-3.0-only"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
# Release binaries are stripped and sanitized by platform build scripts.
strip = true
